<a href="https://colab.research.google.com/github/shreehere/Assignments/blob/main/Jaishree_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.version,np.show_config

(<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>,
 <function numpy.__config__.show()>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
#Creating an array
a=[1,2,3,4,5]

#Creating a 1-dimentional numpy array
m=np.array(a)

#Memory = size of an array * Memory size of one element in an array

print("Size of the array  = ", m.size)
print("Memory size of one element in an array =", m.itemsize)
print("Memory size of the array = ", m.size * m.itemsize)


Size of the array  =  5
Memory size of one element in an array = 8
Memory size of the array =  40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
nv=np.zeros(10)  #creating a null vector of size 10
nv[4]=1   #Assigning the 5th value to 1 using index
nv  #printing the array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v1=np.arange(10,50)
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
v2=np.arange(1,11)
print("An array created with 10 values")
print(v2 ,'\n')
print("Reversed the array using negative index")
v3=v2[::-1]
print(v3)

An array created with 10 values
[ 1  2  3  4  5  6  7  8  9 10] 

Reversed the array using negative index
[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
#Creating an array with values ranging from 0 to 8
M=np.arange(0,9)

#Rearranging the array to a 3X3 matrix
M.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
x

array([[[0.80241218, 0.49330772, 0.88378461],
        [0.07578487, 0.01326311, 0.58010382],
        [0.15301856, 0.17987685, 0.80490798]],

       [[0.40928138, 0.44018815, 0.85008995],
        [0.63094112, 0.42525594, 0.72376915],
        [0.32912955, 0.54550585, 0.28224524]],

       [[0.70166039, 0.67306877, 0.77177407],
        [0.01688031, 0.24734282, 0.19676522],
        [0.7719462 , 0.0968478 , 0.43493587]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print(a,'\n')

#Minimum of a 
print("Minimum of a is ",a.min())
print("Maximum of a is ",a.max())

[[0.69510882 0.1004342  0.63998358 0.10880491 0.115258   0.10835162
  0.5966921  0.82408698 0.35999583 0.37175321]
 [0.63573293 0.11078839 0.38902414 0.37561659 0.5012732  0.91685461
  0.25738304 0.73464736 0.6995827  0.65234601]
 [0.0818107  0.86670165 0.15330503 0.85276556 0.32597998 0.03904214
  0.1304081  0.58400804 0.37053022 0.35394793]
 [0.8203737  0.46423637 0.34358765 0.96765605 0.6293727  0.95262878
  0.27033472 0.69704002 0.4730505  0.94828086]
 [0.47486763 0.66891122 0.63223451 0.27314964 0.25263006 0.11775423
  0.18578718 0.83862709 0.70135573 0.27341701]
 [0.63828925 0.68663245 0.97906181 0.0574757  0.43550545 0.58536453
  0.51991471 0.56451717 0.11965808 0.88618027]
 [0.82008088 0.45300161 0.64324861 0.61478786 0.70589654 0.80600311
  0.74197822 0.04231481 0.00187268 0.4864184 ]
 [0.04422279 0.5581472  0.75522172 0.51424304 0.43100771 0.79069989
  0.12039888 0.48979093 0.07848369 0.31666478]
 [0.04113865 0.88277948 0.87681974 0.89775185 0.2049861  0.4340166
  0.05978573 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x=np.random.random(10)
print(x,'\n')

print('Mean of all the random values is ', x.mean())

[0.05592911 0.48559762 0.14106823 0.65360347 0.28273482 0.45502692
 0.0875125  0.12570442 0.37946423 0.0411873 ] 

Mean of all the random values is  0.2707828643675172


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x=np.ones((5,5))
print(x,'\n')
x=np.pad(x,pad_width=1)
print('Adding a border(filled with 0s) \n',x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Adding a border(filled with 0s) 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan       -   nan 
np.nan == np.nan -   False
np.inf > np.nan  -   False
np.nan - np.nan  -   nan
0.3 == 3 * 0.1   -   False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x=np.diag([1,2,3,4],k=-1)   #k=1 takes the values just below the diagonal
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x= np.ones ((8,8))
x[1::2, ::2]= 0   #From (Row 1 - Row8)+(All columns)-with slicing of 2
x[::2, 1::2] = 0  #From(All Rows)+(Column 1 - Column 8)-with slicing of 2
print (x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr=np.array([[0,1],[1,0]])
x=np.tile(arr,(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
print(x,'\n')
m=x.max()
n=x.min()
x=(x-n)/(m-n)
print('The values are normalized and the higher value becomes 1 and the lower value becomes 0 \n')
print(x)

[[0.70546618 0.26875165 0.07950282 0.25523702 0.59666669]
 [0.78676417 0.40301519 0.12038193 0.18780452 0.70197578]
 [0.35464689 0.83133758 0.47501345 0.39055736 0.32141245]
 [0.03845084 0.07487357 0.80396112 0.04225611 0.21403727]
 [0.75297979 0.92960832 0.89500463 0.78808797 0.42204242]] 

The values are normalized and the higher value becomes 1 and the lower value becomes 0 

[[0.74848201 0.25842886 0.04606591 0.2432636  0.62639418]
 [0.83970942 0.40909083 0.09193783 0.16759516 0.74456531]
 [0.35481501 0.88972686 0.48988268 0.39511144 0.31752144]
 [0.         0.04087126 0.85900675 0.00427003 0.19703188]
 [0.80179875 1.         0.96116995 0.84119491 0.43044197]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
a=np.dtype([('R',np.ubyte,1),('G',np.ubyte,(1,2)),('B',np.ubyte,1),('A',np.ubyte,1)])
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('R', 'u1'), ('G', 'u1', (1, 2)), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.floor(100*np.random.random((5,3)))
print("Creating a 5X3 matrix \n")
print(a,'\n')

b=np.floor(100*np.random.random((3,2)))
print("Creating a 3X2 matrix \n")
print(b,'\n')

p=a.dot(b)
print("Product of a and b")
print(p)

Creating a 5X3 matrix 

[[54. 69. 18.]
 [63.  3. 87.]
 [10. 21. 26.]
 [87. 55. 56.]
 [95. 94.  8.]] 

Creating a 3X2 matrix 

[[90. 23.]
 [10. 10.]
 [67. 51.]] 

Product of a and b
[[ 6756.  2850.]
 [11529.  5916.]
 [ 2852.  1766.]
 [12132.  5407.]
 [10026.  3533.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x=np.arange(10)
print("Created an array of 10 elements")
print(x,'\n')
print("using for loop")
for i in range(3,8):
  x[i]=x[i]*(-1)
print(x,'\n')

print('Another Method')
y=np.arange(10)
print("using the index value with logical operator ")
y[(y>2)&(y<8)]*=-1
print(y)

Created an array of 10 elements
[0 1 2 3 4 5 6 7 8 9] 

using for loop
[ 0  1  2 -3 -4 -5 -6 -7  8  9] 

Another Method
using the index value with logical operator 
[ 0  1  2 -3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) 
print('The statement "print(sum(range(5),-1))" refers the following \n 0+1+2+3+4+(-1) \n') 
from numpy import *
print('Here the statement "print(sum(range(5),-1))" refers the following \n 0+1+2+3+4 - This takes the sum after importing numpy') 
print(sum(range(5),-1))

9
The statement "print(sum(range(5),-1))" refers the following 
 0+1+2+3+4+(-1) 

Here the statement "print(sum(range(5),-1))" refers the following 
 0+1+2+3+4 - This takes the sum after importing numpy
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#All the above are a valid expression

Z<Z>Z  # Not a valid expression 

array([1536,    1,    3,    6,   12])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
x=np.array(0)
print("np.array(0) / np.array(0) \n")
print(x/x,'\n')

print("np.array(0) // np.array(0) \n")
print(x//x,'\n')

print("np.array([np.nan]).astype(int).astype(float) \n")
np.array([np.nan]).astype(int).astype(float)

np.array(0) / np.array(0) 

nan 

np.array(0) // np.array(0) 

0 

np.array([np.nan]).astype(int).astype(float) 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x=[2.7,-9.5,5.2,-4.1,7.1]
x1=[3,8.4,-6.2,7,-8]

y=np.ceil(x)   #Top most value
y

z=np.abs(x)    #Absolute value
z

a=np.copysign(x,x1)  #copying the sign of elements of x1 to elements of x
a


array([ 2.7,  9.5, -5.2,  4.1, -7.1])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a=np.array([1,3,5,5,7,9])
b=np.array([1,2,3,5,6])

print("Common values between a and b with unique values")
d=np.intersect1d(a,b,assume_unique=False)
print(d, '\n')

print("Common values between a and b with repeated values")
c=np.intersect1d(a,b,assume_unique=True)
print(c)

Common values between a and b with unique values
[1 3 5] 

Common values between a and b with repeated values
[1 3 5 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print("The value of np.sqrt(-1) is " , np.sqrt(-1))
print("The value of np.emath.sqrt(-1) is ", np.emath.sqrt(-1))
print("The statement 'np.sqrt(-1) == np.emath.sqrt(-1)' gives the following result")
np.sqrt(-1) == np.emath.sqrt(-1)

The value of np.sqrt(-1) is  nan
The value of np.emath.sqrt(-1) is  1j
The statement 'np.sqrt(-1) == np.emath.sqrt(-1)' gives the following result


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
#For Today's Date
Today=print("Today's Date is",np.datetime64('Today','D'))

#For Tomorrow's Date
Tomorrow=print("Tomorrow's Date is", np.datetime64('Today','D')+np.timedelta64(1,'D'))

#For Yesterday's Date
Tomorrow=print("Yesterday's Date is", np.datetime64('Today','D')+np.timedelta64(-1,'D'))

Today's Date is 2022-11-15
Tomorrow's Date is 2022-11-16
Yesterday's Date is 2022-11-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.array([1,2,-3,4])
B=np.array([2,5,8,9])
print("Adding 2 arrays")
print(np.add(A,B,out=B),'\n')
print("Multiplying 2 arrays")
print(np.multiply(A,B,out=B),'\n')
print("Negate the elements")
print(np.negative(A,out=A),'\n')

#Creating with ones to work on divide
a=np.ones(5)
b=np.ones(5)
print("Dividing the elements")
np.divide(a,2,out=a)

Adding 2 arrays
[ 3  7  5 13] 

Multiplying 2 arrays
[  3  14 -15  52] 

Negate the elements
[-1 -2  3 -4] 

Dividing the elements


array([0.5, 0.5, 0.5, 0.5, 0.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
print('Creating an array with 3X4 matrix with random values \n ')
x=100*np.random.random((3,4))
print(x,'\n')

#x=np.floor(100*np.random.random((3,4)))
#print(x)

print("floor - Rounds off to the least value")
y=np.floor(x)
print(y,'\n')

z=np.ceil(x)
print("ceil - Rounds off with the highest value")
print(z,'\n')

t=np.trunc(x)
print("trunc - Truncates the decimal value")
print(t,'\n')

r=x.astype(int)
print('astype - gives the integer value of elements')
print(r,'\n')

print('using % to round off values')
print(x-x%1)

Creating an array with 3X4 matrix with random values 
 
[[74.31586729 34.30446582 34.4359062  51.13261158]
 [55.50137233 48.00601363 78.10225669 66.24492547]
 [ 2.88736963 80.67280246 97.27828155 43.95271413]] 

floor - Rounds off to the least value
[[74. 34. 34. 51.]
 [55. 48. 78. 66.]
 [ 2. 80. 97. 43.]] 

ceil - Rounds off with the highest value
[[75. 35. 35. 52.]
 [56. 49. 79. 67.]
 [ 3. 81. 98. 44.]] 

trunc - Truncates the decimal value
[[74. 34. 34. 51.]
 [55. 48. 78. 66.]
 [ 2. 80. 97. 43.]] 

astype - gives the integer value of elements
[[74 34 34 51]
 [55 48 78 66]
 [ 2 80 97 43]] 

using % to round off values
[[74. 34. 34. 51.]
 [55. 48. 78. 66.]
 [ 2. 80. 97. 43.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x=np.arange(0,5)
y=np.array([x,x,x,x,x])
y.reshape((5,5))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
#creating a function called generator

def generator():
  for x in range(1,11):
    yield x

#Using fromiter method to generate the elements
y=np.fromiter(generator(),dtype=int)
print(y)



[ 1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x=np.linspace(0,1,10,endpoint=False)[1:]

#endpoint=False is not taking the endpoint we gave here
#we are using the slicing method and removing the start point here

print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
#creating a vector with random elements
print('Random vector of size 10')
v=np.random.randint(1,100,size=10)
print(v,'\n')

#using the sort function to sort it
v.sort()
print('Sorted using the method sort()')
print(v)


Random vector of size 10
[80  9 63 34 96 58 35 66 26 18] 

Sorted using the method sort()
[ 9 18 26 34 35 58 63 66 80 96]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import time

start_time=time.time()    #the start before starting the execution is noted
x=np.arange(100)          #An array created with 100 elements
x=np.sum(x)               #sum of the elements are calculated using sum() method
end_time=time.time()      #the end time after the execution is also noted
Execution_time=end_time-start_time
print("Time taken to execute with np.sum()")
print(1000*Execution_time,'\n')

start_time2=time.time()    #same as above with np.add.reduce() method
y=np.arange(100)
y=np.add.reduce(y)
end_time2=time.time()
Execution_time2=end_time2-start_time2
print("Time taken to execute with np.add.reduce()")
print(1000*Execution_time2,'\n')

print("It is clear that the time taken with the method np.sum() is more than that of with the method np.add.reduce() ")



Time taken to execute with np.sum()
0.8785724639892578 

Time taken to execute with np.add.reduce()
0.1933574676513672 

It is clear that the time taken with the method np.sum() is more than that of with the method np.add.reduce() 


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
#created 2 arrays with the same set of elements
A=np.array([1,3,5,7])
B=np.array([1,3,5,7])
print("Using method np.array_equal")
print(np.array_equal(A,B))

print("Using method np.allclose")
print(np.allclose(A,B))

print("The result is true as the elements are the same")

Using method np.array_equal
True
Using method np.allclose
True
The result is true as the elements are the same


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
print('Creating an array with 5 elements')
x=np.array([1,2,3,4,5])
print(x,'\n')
print('Changing the first index value to 100')
x[1]=100
print(x,'\n')
print("Making the array 'Read-only' using setflags \n")
x.setflags(write=False)
print('Now x has become Read-only and we cannot change the values of elements')
print("Assigning value to an index gives the following error")
x[4]=100


Creating an array with 5 elements
[1 2 3 4 5] 

Changing the first index value to 100
[  1 100   3   4   5] 

Making the array 'Read-only' using setflags 

Now x has become Read-only and we cannot change the values of elements
Assigning value to an index gives the following error


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
#creating a random matrix of 10x2 matrix
print("Random 10x2 matrix created")
z=np.random.random((10,2))
print(x,'\n')
x,y=z[:,0],z[:,1]
print("Cartesian coordinates are rectangular coordinate system")
print("To find the co-ordinates, we need to use the regular trignometry theorem")
print("r=square root of (x^2+y^2)")
print("using the function sqrt \n")
r=np.sqrt(x**2+y**2)
print(r ,'\n')

print("Polar co-ordinates uses both the tetha and the radial distance")
print("It is the inverse tangent function which is the arctangent")
print("using the function arctan2 to get the inverse tangent function \n")
t=np.arctan2(y,x)
print(t)

Random 10x2 matrix created
[0.15597871 0.52612687 0.23874931 0.89383201 0.34289466 0.10385084
 0.47589817 0.78718287 0.71842061 0.92671921] 

Cartesian coordinates are rectangular coordinate system
To find the co-ordinates, we need to use the regular trignometry theorem
r=square root of (x^2+y^2)
using the function sqrt 

[0.54105975 0.92879487 0.68807929 0.62596023 1.02238855 0.85645441
 0.85132205 1.14661968 0.57812862 1.1866514 ] 

Polar co-ordinates uses both the tetha and the radial distance
It is the inverse tangent function which is the arctangent
using the function arctan2 to get the inverse tangent function 

[0.21980612 1.07013331 0.1775162  1.52825019 0.66223588 0.01026502
 0.29427909 0.84581481 0.66255805 0.94843159]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
#creating a random vecotr of size 10
x=np.random.randint(1,100,size=10)
print(x,'\n')

#argmax method gives the index value of the max element
#Assigning the max element to 0
print("Max value replaced to zero")
x[x.argmax()]=0
print(x)

[26 58 58 89 85 61  5 44 42 33] 

Max value replaced to zero
[26 58 58  0 85 61  5 44 42 33]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z=np.ones((3,3),[('x',float),('y',float)])   #creating a 3x3 array and assigning x and y datatype as float
x=np.linspace(0,1,3)   #giving the values of x and y between 0 and 1
y=np.linspace(0,1,3)
z['x'],z['y']=np.meshgrid(x,y)  #using meshgrid to create z with x and y co-ordinates
print(z)


[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
#Cauchy matrix is an m×n matrix with elements aij in the form
#aij=1/xi-yj  where i and j >1 , i<m and j<n

print("Cauchy Matrix")
print("Matrix - x")
x = np.random.random((3,3))
print(x, '\n')
print("Matrix - y")
y = np.random.random((3,3))
print(y, '\n')
print("Cauchy matrix = aij=1/xi-yj")
z=np.subtract.outer(x,y)
c = 1 / z
#using linear algebra to compute the determinant of an array
print("linalg method is used to compute the determinant of an array")
print(np.linalg.det(c))

Cauchy Matrix
Matrix - x
[[0.62070252 0.44263946 0.60391274]
 [0.16563792 0.32023522 0.36945902]
 [0.55693712 0.80891827 0.80033218]] 

Matrix - y
[[0.18760144 0.61110621 0.50972593]
 [0.80636747 0.44170362 0.29148364]
 [0.88574843 0.10347891 0.90361207]] 

Cauchy matrix = aij=1/xi-yj
linalg method is used to compute the determinant of an array
[[ -3141.18430111 -44866.85366082   3932.54496136]
 [ -5976.35154996   -752.92436636    250.37479223]
 [   706.47414624  22727.13592332  -9354.3388381 ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16



#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
x=np.arange(1001)
print("Values printed in a single line with three dots...")
print(x,'\n')

from numpy import sys   #importing sys to use the maxsize
np.set_printoptions(threshold=sys.maxsize) #using set_printoptions
print("Now printing all the values here")
print(x)

Values printed in a single line with three dots...
[   0    1    2 ...  998  999 1000] 

Now printing all the values here
[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
#Generated an array ranging from 0 to 100
Z = np.arange(100)
print("Random array z is created ranging 0 to 100 \n")

#Randomly generating a float value
i = np.random.uniform(0,100)
print("Random float value created within 100")
print(i,'\n')

#using minimum index value to the closest
print("Minimum element index value of the closest using argmin")
index = (np.abs(Z-i)).argmin()
print(Z[index],'\n')

#using maximum index value to the closest
print("Maximum element index value of the closest using argmax")
index1=(np.abs(Z+i)).argmax()
print(Z[index])

Random array z is created ranging 0 to 100 

Random float value created within 100
88.59131335382027 

Minimum element index value of the closest using argmin
89 

Maximum element index value of the closest using argmax
89


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
#Creating a structured array with size 12
z = np.ones(12, [ ('position', [ ('x', int),
                                  ('y', int)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])]).reshape(4,3)
                                  #reshaping to 4x3 array
print(z)

[[((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.))]
 [((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.))]
 [((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.))]
 [((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.)) ((1, 1), (1., 1., 1.))]]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
v = np.random.random((100, 2))        #random vector created in shape(100,2)
x,y = np.atleast_2d(v[:,0], v[:,1])   #vector is converted to 2-dimensional
distance = np.sqrt((x-x.T)**2 + (y-y.T)**2)   #formula used to find the distance
print(distance)

[[0.         0.79386062 0.07402388 0.38341611 0.65886615 0.93531665
  0.6260326  0.41570803 0.76750358 0.55145241 0.41467622 0.64635163
  0.90723031 0.78770387 0.67040211 0.70969747 0.65907135 0.66889673
  0.70821877 0.87535924 0.92669296 0.35812193 0.90316179 0.712835
  0.79623303 1.03694813 0.34798357 0.42338435 0.41344607 0.50792698
  0.56867968 0.84437364 1.17611528 1.0218338  0.20974636 0.29440524
  0.60104083 0.93353285 0.98023967 0.40036081 0.60823757 0.93692692
  0.35657088 1.05791834 0.1708523  0.65513493 0.72752502 0.17066469
  0.7424875  0.79516563 0.8826102  0.50529698 0.18905813 0.69847716
  0.3435699  0.43958638 0.57366731 0.35952879 0.25154567 0.96523164
  0.13559247 0.49878872 0.78362571 0.22151197 1.0779325  0.99249087
  1.11125454 0.7693134  0.79904465 0.84348425 0.22766364 0.88083129
  0.7416034  0.77729894 0.14925202 0.81594172 0.70985157 0.55457157
  0.58877779 0.72046392 0.7982592  0.73799668 0.77174465 0.92579852
  0.48613135 0.568255   1.09583338 0.20610173 1.01

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
#creating a variable x with random values
x=10*np.random.random((1,5))
x=x.astype(np.float32)  #changin the data type to float32
print(x)

#converting the values to int32
x=x.astype(np.int32,copy=False)
print(x)

[[1.2173523 8.689062  7.7796183 0.7592318 7.193909 ]]
[[1 8 7 0 7]]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
#importing Input/output package
from io import StringIO

#variable assigned to the data
data="""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

print("without mentioning the dtype, the missing values are nan")
text=np.genfromtxt(StringIO(data),delimiter=',')
print(text,'\n')

print("with the dtype as int and the missing values as 0")
text1=np.genfromtxt(StringIO(data),delimiter=",",dtype=np.int,filling_values=0)
print(text1)

without mentioning the dtype, the missing values are nan
[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]] 

with the dtype as int and the missing values as 0
[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
#We can use ndindex equivalent to enumerate

print("An array created with the range of 4 elements and reshaped")
x = np.arange(4).reshape(2,2)
print(x,'\n')
print("Using np.ndenumerate \n") 
print(list(np.ndenumerate(Z)),'\n')
print("Using np.ndindex\n")
Result=[]
for index in np.ndindex(x.shape):
    Result.append((index, x[index]))
print(Result)

An array created with the range of 4 elements and reshaped
[[0 1]
 [2 3]] 

Using np.ndenumerate 

[((0,), (([1, 1, 1, 1, 1], [1, 1]), (1., 1., 1.))), ((1,), (([1, 1, 1, 1, 1], [1, 1]), (1., 1., 1.))), ((2,), (([1, 1, 1, 1, 1], [1, 1]), (1., 1., 1.)))] 

Using np.ndindex

[((0, 0), 0), ((0, 1), 1), ((1, 0), 2), ((1, 1), 3)]


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
#Gaussian formula:   f(x,μ,σ)=1σ2π−−√e−(x−mu)22σ2

x, y = np.meshgrid(np.linspace(1,2,5), np.linspace(1,2,5))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like Array")
print(g)

2D Gaussian-like Array
[[0.36787944 0.27768997 0.19691168 0.13117145 0.082085  ]
 [0.27768997 0.20961139 0.14863673 0.09901341 0.06196101]
 [0.19691168 0.14863673 0.10539922 0.07021102 0.04393693]
 [0.13117145 0.09901341 0.07021102 0.04677062 0.02926831]
 [0.082085   0.06196101 0.04393693 0.02926831 0.01831564]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5   
p = 10  #number of elements to be placed
x= np.ones((n, n))   #generated the matrix with element values of 1
np.put(x, np.random.choice(range(n*n), p, replace=False), 777)   #specified the value to be replaced as 777
print("Randomly placed 777 in 10 places in the matrix \n")
print(x)

Randomly placed 777 in 10 places in the matrix 

[[  1.   1.   1. 777.   1.]
 [777.   1. 777. 777. 777.]
 [777.   1.   1. 777.   1.]
 [777. 777.   1. 777.   1.]
 [  1.   1.   1.   1.   1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
print("Random values of 3x4 matrix created \n")
x=np.random.rand(3,4)
print(x,'\n')

x_mean=x.mean(axis=1,keepdims=True)
x=x-x_mean
print("Mean subtracted for each row of the matrix \n")
print(x)

Random values of 3x4 matrix created 

[[0.00418531 0.41281158 0.24547158 0.43436853]
 [0.5136018  0.28109415 0.08788459 0.62895368]
 [0.98247503 0.92967076 0.45450915 0.51123057]] 

Mean subtracted for each row of the matrix 

[[-0.27002394  0.13860233 -0.02873767  0.16015928]
 [ 0.13571824 -0.0967894  -0.28999896  0.25107012]
 [ 0.26300365  0.21019938 -0.26496223 -0.20824081]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
#created a random integer matrix
x = np.random.randint(1,25,(3,4))
print("Random integer matrix")
print(x,'\n')
print("sorting based on the 2nd column")
print(x[x[:,1].argsort()],'\n')
print("sorted based on the 3rd column")
print(x[x[:,2].argsort()])

Random integer matrix
[[11  2  8  1]
 [16 13  5  5]
 [ 6  2 15  8]] 

sorting based on the 2nd column
[[11  2  8  1]
 [ 6  2 15  8]
 [16 13  5  5]] 

sorted based on the 3rd column
[[16 13  5  5]
 [11  2  8  1]
 [ 6  2 15  8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
#Random array created
x=np.random.randint(0,4,(3,4))
print("Random array")
print(x)
print((~x.any(axis=0)).any())
print("Values with all values as 0 will be resulted as True \n")

print("Array created with second column as 0")
y=np.array([1,0,2,4,0,7,8,0,1]).reshape(3,3)
print(y)
print((~y.any(axis=0)))
print("Here the second column resulted as True as all the values are 0 \n")

print("Example with an array with nan values")
z=np.array([
    [0,1,np.nan],
    [1,2,np.nan]
])
print(z)
print(np.isnan(z).all(axis=0))

Random array
[[2 2 3 2]
 [3 1 2 2]
 [0 3 0 0]]
False
Values with all values as 0 will be resulted as True 

Array created with second column as 0
[[1 0 2]
 [4 0 7]
 [8 0 1]]
[False  True False]
Here the second column resulted as True as all the values are 0 

Example with an array with nan values
[[ 0.  1. nan]
 [ 1.  2. nan]]
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
#created a random array
x = np.random.uniform(0,1,10)
print(x,'\n')
n = 0.5   #Defining a value to find out the closest
i_min = np.abs(x-n).argmin()
print("The nearest value to n=0.5 is ")
print(x[i_min])

[0.27850226 0.07789562 0.17840007 0.49620618 0.55202004 0.45133449
 0.42227416 0.31109998 0.31047865 0.99581799] 

The nearest value to n=0.5 is 
0.49620618009768536


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x=np.arange(3).reshape(1,3)
print("x- Array \n")
print(x,'\n')
y=np.arange(3).reshape(3,1)
print("y- Array \n")
print(y,'\n')
#creating iterations
i=np.nditer([x,y,None])
print("Iterator object i created with x,y and an empty set")
print(i,'\n')

#Appending to Z
print("Computing the sum of x and y with the iterator i")
for x,y,z in i:
  z[...]=x+y
print(i.operands[2])

x- Array 

[[0 1 2]] 

y- Array 

[[0]
 [1]
 [2]] 

Iterator object i created with x,y and an empty set

Computing the sum of x and y with the iterator i
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
#class defined with the functions
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

#Calling the NamedArray
Z = NamedArray(np.arange(5), "arangeof5")

print('Z-array')
print(Z,'\n')
print('Name of the Z-array')
print (Z.name)

Z-array
[0 1 2 3 4] 

Name of the Z-array
arangeof5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
#Array creted with all 1s, size of 10
x = np.ones(10)
print("Original Array - 1st: ")
print(x,'\n')

#This vector holds 10 (Length of the array, x) in the range of random values between 0 and 20
y = np.random.randint(0, len(x), 20) 
print("The Second array: ")
print(y,'\n')

'''
The np.bincount() is a numpy library method used to obtain the frequency of each element provided inside a numpy array. 
The numpy bincount() method takes arr_name, weights, and minlength as arguments and returns the ndarray of integers.
'''
bin_count = np.bincount(y, minlength=len(x))
print("The bin_count: ")
print(bin_count,'\n')

Result = x + bin_count
print("Result after the summation")
print(Result,'\n')

print("--------------------------------")
print("Another Method using np.add.at")
np.add.at(x, y, 1)
print(x)


Original Array - 1st: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

The Second array: 
[3 5 9 2 8 2 4 4 4 6 3 6 4 7 3 7 2 2 5 5] 

The bin_count: 
[0 0 4 3 4 3 2 2 1 1] 

Result after the summation
[1. 1. 5. 4. 5. 4. 3. 3. 2. 2.] 

--------------------------------
Another Method using np.add.at
[1. 1. 5. 4. 5. 4. 3. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
print("Array - X")
X=[88,33,98,21,18,3,78]
print(X,'\n')
print("Array - Y")
Y=[1,2,4,7,9,3,0]
print(Y,'\n')
print("Elements accumulated based on an Index List Y")
print("Array - F")
F=np.bincount(Y,X)
print(F)


Array - X
[88, 33, 98, 21, 18, 3, 78] 

Array - Y
[1, 2, 4, 7, 9, 3, 0] 

Elements accumulated based on an Index List Y
Array - F
[78. 88. 33.  3. 98.  0.  0. 21.  0. 18.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
#Assigning the values for w and h
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
print("The number of unique colors")
n = len(np.unique(I24))
print(n)


The number of unique colors
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x = np.random.randint(0,20,(2,2,2,2))
print("******4D array******")
print(x,'\n')
#passing a tuple of axes
sum = x.sum(axis=(-2,-1))
print('Sum over the last two axis at once: ', sum)

******4D array******
[[[[ 0 15]
   [14  5]]

  [[16  3]
   [15 13]]]


 [[[10  9]
   [ 9  8]]

  [[ 8  5]
   [19  0]]]] 

Sum over the last two axis at once:  [[34 47]
 [36 32]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
print("ndarray : D")
D = np.random.uniform(0,1,31)
print(D)
print('--------------------------------------------')
S = np.random.randint(0,10,31)
print("ndarray :S")
print(S)
print('-------------------------------------------')
D_sums = np.bincount(S, weights=D) 
D_counts = np.bincount(S)
D_means = D_sums / D_counts  
print("Means of the subsets of D using S")
print(D_means)

ndarray : D
[0.53408311 0.7752947  0.56767356 0.73075935 0.07125541 0.3023702
 0.58410565 0.32811434 0.19364256 0.15915055 0.00494197 0.06806802
 0.48664469 0.94862442 0.22027098 0.80497244 0.82710339 0.79063492
 0.41559628 0.63786382 0.87938804 0.96380142 0.2022936  0.31662628
 0.57642958 0.08694666 0.135011   0.03658527 0.38506411 0.78067929
 0.57741496]
--------------------------------------------
ndarray :S
[7 9 5 8 9 8 2 9 7 0 2 0 6 2 6 9 6 0 5 0 4 6 9 6 1 6 3 9 8 3 0]
-------------------------------------------
Means of the subsets of D using S
[0.44662645 0.57642958 0.51255735 0.45784515 0.87938804 0.49163492
 0.48356557 0.36386283 0.47273122 0.36975263]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x=np.random.randint(1,10,size=(2,2))
print("x: 2x2 Array")
print(x, '\n')
y=np.random.randint(1,10,size=(2,2))
print("y: 2x2 Array")
print(y,'\n')
print("z: Product of x and y")
z=x.dot(y)
print(z,'\n')
print("Diagonal of the resultant array z")
d=np.diag(z)
print(d)

x: 2x2 Array
[[1 6]
 [3 7]] 

y: 2x2 Array
[[6 5]
 [5 4]] 

z: Product of x and y
[[36 29]
 [53 43]] 

Diagonal of the resultant array z
[36 43]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
print("Using for loop")

x=[1,2,3,4,5]

for i in range(0,4):
  x[i]=i+1,0,0,0

print("Added 3 zeros using for loop")
print(x)
L=[]  #Empty list created here
for i in x:
   if type(i)!=int:
       for j in range(len(i)):
          L.append(i[j])
   else:
       L.append(i)

print("Tuple values are added to the list L")
print(L,'\n')
print('------------------------------')

print("Using slicing method")

Z = np.array([1,2,3,4,5])
nz = 3 #Number of zeros should be placed between each value in the vector
Z_len = len(Z)
print("Length of Z : ", Z_len,'\n')

Z0 = np.zeros(Z_len + (Z_len-1)*(nz)) #Initializing a Zero vector of size (Length of the vector + the number of zeros between each value)
print("Initialized zero array for the required length")
print("Zero Array : ")
print(Z0,'\n')
print("Equated the values of Z for every 4th element")
Z0[::nz+1] = Z
print(Z0)

Using for loop
Added 3 zeros using for loop
[(1, 0, 0, 0), (2, 0, 0, 0), (3, 0, 0, 0), (4, 0, 0, 0), 5]
Tuple values are added to the list L
[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5] 

------------------------------
Using slicing method
Length of Z :  5 

Initialized zero array for the required length
Zero Array : 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Equated the values of Z for every 4th element
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
print("Array A : ")
print(A,'\n')

B = 2*np.ones((5,5))
print("Array B : ")
print(B,'\n')

print("Multiplication between A and B :")
print(A * B[:,:,None])

Array A : 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 

Array B : 
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] 

Multiplication between A and B :
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
print('Array-y')
y=np.arange(25).reshape(5,5)
print(y,'\n')
print('Using index values to swap the first two rows')
y[[0,1]]=y[[1,0]]
print(y)

Array-y
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Using index values to swap the first two rows
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8, 17) ( 8, 42) (10, 52) (10, 72) (12, 27) (12, 37) (12, 46) (12, 97)
 (14, 47) (14, 71) (17, 42) (17, 81) (17, 91) (20, 23) (20, 51) (20, 64)
 (20, 65) (20, 68) (20, 74) (23, 74) (27, 97) (37, 46) (47, 71) (51, 68)
 (52, 72) (61, 86) (61, 89) (64, 65) (81, 91) (86, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
print('C-Array')
C = np.bincount([1,1,2,3,4,4,6]) 
print(C,'\n')
print("Array with the length of C")
print(np.arange(len(C)),"\n")
print("Array A, produced to match C using repeat method")
A = np.repeat(np.arange(len(C)), C)
print(A,'\n')
print("np.bincount(A)",np.bincount(A)," = " , " C ",C)

C-Array
[0 2 1 1 2 0 1] 

Array with the length of C
[0 1 2 3 4 5 6] 

Array A, produced to match C using repeat method
[1 1 2 3 4 4 6] 

np.bincount(A) [0 2 1 1 2 0 1]  =   C  [0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def avg(a, n=2) :
    ret = np.cumsum(a, dtype=float)
    print("cumulative summation")
    print(ret,'\n')
    ret[n:] = ret[n:] - ret[:-n]
    print('Array after moving average')
    return ret[n - 1:] / n
   
Z = np.arange(10)
print("Array Z")
print(Z,'\n')
print(avg(Z, n=2),'\n')
print('--------------------------------------')

print("Another Method")
print('Using sliding_window_view')
from numpy.lib.stride_tricks import sliding_window_view
x=np.arange(10)
print(sliding_window_view(x,window_shape=2).mean(axis=-1))


Array Z
[0 1 2 3 4 5 6 7 8 9] 

cumulative summation
[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.] 

Array after moving average
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5] 

--------------------------------------
Another Method
Using sliding_window_view
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
from numpy.lib.stride_tricks import sliding_window_view

x=np.arange(10)
print(x)
print(sliding_window_view(x,window_shape=3))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,10)
print("Z- Random Array with size 10")
print(Z,'\n')
print("Negate the Boolean using np.logical_not")
print(np.logical_not(Z, out=Z),'\n')
print("----------------------------")

x = np.random.uniform(-1.0,1.0,10)
print("x-Random Array with size 10")
print(x,'\n')
print("Changing the sign using np.negative")
print(np.negative(x, out=x))

Z- Random Array with size 10
[1 1 0 0 1 0 1 1 1 0] 

Negate the Boolean using np.logical_not
[0 0 1 1 0 1 0 0 0 1] 

----------------------------
x-Random Array with size 10
[-0.3404951  -0.52318616 -0.60557592  0.30443308 -0.80857901 -0.91612931
  0.77420394 -0.79124905 -0.93098118  0.76467883] 

Changing the sign using np.negative
[ 0.3404951   0.52318616  0.60557592 -0.30443308  0.80857901  0.91612931
 -0.77420394  0.79124905  0.93098118 -0.76467883]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(3,2))
print("Point P0")
print(P0)
print("-----------------------------")
P1 = np.random.uniform(-10,10,(3,2))
print("Point P1")
print(P1)
print("-----------------------------")
p = np.random.uniform(-10,10,( 1,2))
print("Point p")
print(p)
print("------------------------------")
distance_result = distance(P0, P1, p)
print("Distance Result")
print(distance_result)

Point P0
[[-6.41713064  5.34168437]
 [ 8.32090282  6.52233652]
 [-5.7612222  -6.89389881]]
-----------------------------
Point P1
[[-5.677229   -1.62169363]
 [ 7.10883078  1.45262225]
 [ 2.15099899  0.03891797]]
-----------------------------
Point p
[[-6.73129287  2.0255158 ]]
------------------------------
Distance Result
[ 0.6627944  13.59397642  7.34779692]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10,(3,2))
print("Point P0")
print(P0)
print("--------------------------------")
P1 = np.random.uniform(-10,10,(3,2))
print("Point P1")
print(P1)
print("---------------------------------")
p = np.random.uniform(-10, 10,(3,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

Point P0
[[-4.12587942e-01 -6.85082585e+00]
 [-4.50222212e+00 -7.33243234e+00]
 [ 1.50858168e-03 -9.36255680e+00]]
--------------------------------
Point P1
[[ 9.71638369  4.73769351]
 [-3.61376614 -7.99623315]
 [ 8.46223841  0.35503646]]
---------------------------------
[[ 6.87393007  0.57840969  8.8431597 ]
 [ 8.07601311 13.79440781 10.01765855]
 [ 3.75206785  7.41294018  1.79982407]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 1 9 3 9 5 1 3 7 2]
 [6 2 9 4 3 1 0 7 8 1]
 [0 7 0 6 1 2 2 1 3 7]
 [4 9 9 4 5 7 6 3 2 7]
 [9 8 4 2 0 3 2 7 4 1]
 [8 1 4 0 6 1 0 6 1 0]
 [0 3 7 0 2 7 4 4 0 0]
 [6 8 6 7 6 4 1 4 7 3]
 [7 0 6 6 2 3 0 9 2 9]
 [8 4 4 8 9 1 2 5 6 8]]
[[0 0 0 0 0]
 [0 2 1 9 3]
 [0 6 2 9 4]
 [0 0 7 0 6]
 [0 4 9 9 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(1,15,dtype=np.int32)
print("Initialized Array : ")
print(Z)
print("-----------------------------------------")
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print("The result after applying Strides : ")
print(R)

Initialized Array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-----------------------------------------
The result after applying Strides : 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
print("Random array - Z ")
print(Z,'\n')
Z = np.random.uniform(0,1,(3,3))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print("Rank using np.linalg.svd")
print(rank)

print("-----------------------")

rank = np.linalg.matrix_rank(Z)
print("Rank using np.linalg.matrix_rank")
print(rank)

Random array - Z 
[[0.7129101  0.42083812 0.98983792]
 [0.12010281 0.22715104 0.87017638]
 [0.71608892 0.72779263 0.65913865]] 

Rank using np.linalg.svd
3
-----------------------
Rank using np.linalg.matrix_rank
3


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print("Initialized Array : ")
print(Z)
print("--------------------------------")
frequent_value = np.bincount(Z).argmax()
print("Most frequent value in the array")
print(frequent_value)

Initialized Array : 
[1 9 7 0 0 0 4 8 9 9 2 1 5 0 2 6 3 1 7 5 1 5 6 8 2 8 0 5 3 7 3 4 1 8 4 0 8
 6 8 4 7 0 1 1 2 5 1 3 5 3]
--------------------------------
Most frequent value in the array
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
print("Initialized Array : ")
print(Z)
print("-------------------------")
print(sliding_window_view(Z, window_shape=(3, 3)))

Initialized Array : 
[[3 3 2 2 1 3 1 2 1 0]
 [2 2 3 2 2 4 4 3 3 1]
 [1 2 3 2 1 0 0 2 4 4]
 [2 4 0 1 2 3 4 1 0 4]
 [1 4 3 4 0 4 4 0 2 4]
 [0 0 2 0 3 2 4 4 0 1]
 [1 2 2 1 2 0 0 0 4 4]
 [4 4 3 4 1 4 0 1 3 2]
 [0 2 0 1 4 1 2 3 4 1]
 [2 2 0 3 3 0 3 1 3 1]]
-------------------------
[[[[3 3 2]
   [2 2 3]
   [1 2 3]]

  [[3 2 2]
   [2 3 2]
   [2 3 2]]

  [[2 2 1]
   [3 2 2]
   [3 2 1]]

  [[2 1 3]
   [2 2 4]
   [2 1 0]]

  [[1 3 1]
   [2 4 4]
   [1 0 0]]

  [[3 1 2]
   [4 4 3]
   [0 0 2]]

  [[1 2 1]
   [4 3 3]
   [0 2 4]]

  [[2 1 0]
   [3 3 1]
   [2 4 4]]]


 [[[2 2 3]
   [1 2 3]
   [2 4 0]]

  [[2 3 2]
   [2 3 2]
   [4 0 1]]

  [[3 2 2]
   [3 2 1]
   [0 1 2]]

  [[2 2 4]
   [2 1 0]
   [1 2 3]]

  [[2 4 4]
   [1 0 0]
   [2 3 4]]

  [[4 4 3]
   [0 0 2]
   [3 4 1]]

  [[4 3 3]
   [0 2 4]
   [4 1 0]]

  [[3 3 1]
   [2 4 4]
   [1 0 4]]]


 [[[1 2 3]
   [2 4 0]
   [1 4 3]]

  [[2 3 2]
   [4 0 1]
   [4 3 4]]

  [[3 2 1]
   [0 1 2]
   [3 4 0]]

  [[2 1 0]
   [1 2 3]
   [4 0 4]]

  [[1 0 0]
   [2 3

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

print("Symmetric random matrix 3x3 is created")
S = symetric(np.random.randint(0,10,(3,3)))
print(S,"\n")
print("changing the element of index value(1,2) and (2,1) to 1000")
S[1,2] = 1000
print(S)

Symmetric random matrix 3x3 is created
[[ 1 12 14]
 [12  0 12]
 [14 12  6]] 

changing the element of index value(1,2) and (2,1) to 1000
[[   1   12   14]
 [  12    0 1000]
 [  14 1000    6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
print("Value of p=2 \nValue of n=3 \n")
p, n = 2, 3
M = np.ones((p,n,n))
print("M-Array")
print(M,'\n')
V = np.ones((p,n,1))
print("V-Array")
print(V,"\n")
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print("S-Array")
print(S)

Value of p=2 
Value of n=3 

M-Array
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 

V-Array
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]] 

S-Array
[[6.]
 [6.]
 [6.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.random.randint(1,10,(16,16))
print("Z-Random Array")
print(Z)
k = 4
print("Using np.add.reduceat")
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z-Random Array
[[7 4 2 3 6 3 3 3 8 3 1 3 9 5 9 3]
 [6 7 1 3 9 5 4 1 1 8 9 9 7 5 3 5]
 [4 5 2 6 9 1 5 2 8 2 2 2 1 2 7 6]
 [3 1 6 8 9 6 8 6 5 3 3 7 2 5 6 2]
 [4 4 2 7 1 7 8 4 5 6 3 8 8 5 6 2]
 [1 8 5 7 4 2 9 6 1 5 4 8 6 1 8 9]
 [7 8 2 9 1 4 4 9 3 4 5 1 1 6 6 5]
 [7 4 1 7 3 5 8 6 7 7 2 5 2 9 2 6]
 [2 2 9 4 1 3 7 7 4 7 3 4 4 4 5 6]
 [7 5 2 2 9 4 8 6 3 5 8 7 8 9 7 3]
 [3 1 4 9 6 5 1 8 8 3 6 5 8 5 1 9]
 [9 2 5 2 3 5 5 8 5 1 7 2 8 1 1 9]
 [2 5 6 4 4 3 7 1 1 2 3 8 4 8 4 9]
 [7 2 6 3 6 1 8 5 6 1 1 9 1 3 5 3]
 [8 7 2 6 4 9 3 6 4 6 3 1 4 1 5 3]
 [3 6 9 1 8 1 3 8 1 9 7 2 6 6 8 9]]
Using np.add.reduceat
[[68 80 74 77]
 [83 81 74 82]
 [68 86 78 88]
 [77 77 64 79]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
print("Z-Array")
print("Z- An array from the range 1-100")
Z = np.arange(1,101)
print(Z,"\n")

np.random.shuffle(Z)
n = 8
print("n=8; Taking the last 8 values after sorting \n ")
print("Using np.argsort")
print (Z[np.argsort(Z)[-n:]],'\n')

print("Using np.argpartition")
print (Z[np.argpartition(-Z,n)[:n]])

Z-Array
Z- An array from the range 1-100
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

n=8; Taking the last 8 values after sorting 
 
Using np.argsort
[ 93  94  95  96  97  98  99 100] 

Using np.argpartition
[ 95  99 100  97  96  98  94  93]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print("Cartesian Product of 3 x 1 x 2")
print("6 rows and 3 colums created with every combinations")
print (cartesian(([1, 2, 3],[2],[1, 0])))

Cartesian Product of 3 x 1 x 2
6 rows and 3 colums created with every combinations
[[1 2 1]
 [1 2 0]
 [2 2 1]
 [2 2 0]
 [3 2 1]
 [3 2 0]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print("Result")
print(result,'\n')
print("Result[0] :", result[0],'\n')
print("Result[1] :", result[1],'\n')
print("Result[2] :", result[2],'\n')
print("Result[3] :", result[3])

Result
[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )] 

Result[0] : (1, 'Red', 12.2) 

Result[1] : (2, 'Green', 15.) 

Result[2] : (3, 'White', 20.) 

Result[3] : (4, 'Orange', 40.)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

print("Using np.power method")
print(np.power(x,3),'\n')

print("Using normal multiplication method")
print(x*x*x,'\n')

print("Using np.einsum")
print(np.einsum('i,i,i->i',x,x,x))

Using np.power method
[0.53359066 0.24729354 0.03904951 ... 0.07386672 0.00266819 0.0023081 ] 

Using normal multiplication method
[0.53359066 0.24729354 0.03904951 ... 0.07386672 0.00266819 0.0023081 ] 

Using np.einsum
[0.53359066 0.24729354 0.03904951 ... 0.07386672 0.00266819 0.0023081 ]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
nums1 = np.random.randint(5,10,(6,4))
nums2 = np.random.randint(5,10,(2,3))
print("Original arrays:")
print(nums1)
print("\n",nums2)
temp = (nums1[..., np.newaxis, np.newaxis] == nums2)
rows = (temp.sum(axis=(1,2,3)) >= nums2.shape[1]).nonzero()[0]
print("\nRows of a given array that contain elements of each row of another given array:")
print(rows)

Original arrays:
[[7 6 7 8]
 [8 8 8 7]
 [8 6 9 6]
 [9 5 5 9]
 [7 8 6 8]
 [9 7 7 9]]

 [[9 6 8]
 [7 9 7]]

Rows of a given array that contain elements of each row of another given array:
[0 1 2 3 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
x = np.random.randint(0,10,(5,3))
x1=np.ones(15).reshape(5,3)
#created an array with the same values to show the difference
y=np.vstack((x,x1))   #used horizontal stack to stack it with the x matrix
print("Original vector:")
print(y)
new_y = np.logical_and.reduce(y[:,1:] == y[:,:-1], axis=1)
result = y[~new_y]
print("\nRows with unequal values:")
print(result)

Original vector:
[[1. 0. 6.]
 [2. 1. 0.]
 [1. 0. 4.]
 [7. 2. 5.]
 [3. 7. 4.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Rows with unequal values:
[[1. 0. 6.]
 [2. 1. 0.]
 [1. 0. 4.]
 [7. 2. 5.]
 [3. 7. 4.]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
x = np.array([8, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
x = np.random.randint(0,10,(3,3))
x1=np.ones(9).reshape(3,3)
#created an array with the same values to show the difference
y=np.vstack((x,x1))   #used horizontal stack to stack it with the x matrix
print("Original vector:")
print(y,'\n')
print("------------------------")
print("Unique Rows are displayed using np.unique method")
u = np.unique(y, axis=0)
print(u)

Original vector:
[[2. 8. 8.]
 [1. 5. 8.]
 [4. 6. 7.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

------------------------
Unique Rows are displayed using np.unique method
[[1. 1. 1.]
 [1. 5. 8.]
 [2. 8. 8.]
 [4. 6. 7.]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.array([0, 1, 2])

B = np.array([4, 5, 6])

print("np.einsum")
print(np.einsum('i->', A),'\n')

print("Multiplication function")
print(np.einsum('i,i->i', A, B),'\n')

print("Inner product or the Dot product")
print(np.einsum('i,i', A, B),'\n')

print("Outer product")
print(np.einsum('i,j->ij', A, B))

np.einsum
3 

Multiplication function
[ 0  5 12] 

Inner product or the Dot product
17 

Outer product
[[ 0  0  0]
 [ 4  5  6]
 [ 8 10 12]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
print("Equidistant:")
print("------------")
print("A point is equidistant from 2 other points when it is always the same distance away from those points.\nExample: point B is equidistant from points A and C. \n")

print("Distance formula")
print("----------------")
print("d = √[(x2−x1)2+(y2−y1)2] √ [ ( x 2 − x 1 ) 2 + ( y 2 − y 1 ) 2 ] \n")

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 5) 
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

print("r_int: ", r_int,'\n')
print("x_int, y_int")
print("------------")
for i in range(len(x_int)):
  for j in range(len(y_int)):
    print(x_int[i],y_int[j])

Equidistant:
------------
A point is equidistant from 2 other points when it is always the same distance away from those points.
Example: point B is equidistant from points A and C. 

Distance formula
----------------
d = √[(x2−x1)2+(y2−y1)2] √ [ ( x 2 − x 1 ) 2 + ( y 2 − y 1 ) 2 ] 

r_int:  [  0.         123.7724568  247.54491359 371.31737039 495.08982719] 

x_int, y_int
------------
0.0 0.0
0.0 1.5054772837517967
0.0 -3.6940816250278914
0.0 24.191900161063277
0.0 -0.500072085643085
-15.53063667594265 0.0
-15.53063667594265 1.5054772837517967
-15.53063667594265 -3.6940816250278914
-15.53063667594265 24.191900161063277
-15.53063667594265 -0.500072085643085
-21.821431128409632 0.0
-21.821431128409632 1.5054772837517967
-21.821431128409632 -3.6940816250278914
-21.821431128409632 24.191900161063277
-21.821431128409632 -0.500072085643085
-12.321022161747202 0.0
-12.321022161747202 1.5054772837517967
-12.321022161747202 -3.6940816250278914
-12.321022161747202 24.191900161063277
-12.32102216

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
x = np.random.randint(1,10,(5,5))
x1=np.ones(10).reshape(2,5)
y=np.vstack((x,x1))
print("Original Array")
print(y,'\n')

print("stating n=5; The summation of all the elements to 5 is our result \n")
n = 5
M = np.logical_and.reduce(np.mod(y, 1) == 0, axis=-1)
M &= (y.sum(axis=-1) == n)
print("Using np.logical_and.reduce, np.mod methods \n")
print("Here last 2 rows are summing to 5 and it came out 'True'")
print(M,'\n')
print("The rows with the summation of 5:")
print(y[M])

Original Array
[[6. 7. 3. 7. 8.]
 [5. 4. 8. 9. 4.]
 [1. 2. 7. 3. 7.]
 [3. 5. 9. 8. 8.]
 [6. 2. 6. 3. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

stating n=5; The summation of all the elements to 5 is our result 

Using np.logical_and.reduce, np.mod methods 

Here last 2 rows are summing to 5 and it came out 'True'
[False False False False False  True  True] 

The rows with the summation of 5:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [4]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print("Bootstrapped 95% confidence intervals for the mean of 1D array X")
print(confint)

Bootstrapped 95% confidence intervals for the mean of 1D array X
[-0.06373265  0.29824701]
